accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

assignments/urls.py
from django.urls import path
from . import views

app_name = 'assignments'

urlpatterns = [
    path('', views.assignment_list, name="list"),
    path('create/', views.assignment_create, name="create"),
    path('<slug:slug>/', views.assignment_detail, name="detail"),
]

matcha/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from assignments import views as assignment_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', assignment_views.assignment_list, name="home"),
    path('assignments/', include('assignments.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

assignments/models.py
from django.db import models
from django.contrib.auth.models import User


class Assignment(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

assignments/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Assignment
        fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('assignments:list')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('assignments:list')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('assignments:list')

assignments/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Assignment
from django.contrib.auth.decorators import login_required
from . import forms


def assignment_list(request):
    assignments = Assignment.objects.all().order_by('date')
    return render(request, 'assignments/assignment_list.html', {'assignments': assignments})


def assignment_detail(request, slug):
    assignment = Assignment.objects.get(slug=slug)
    return render(request, 'assignments/assignment_detail.html', {'assignment': assignment})


@login_required(login_url="/accounts/login/")
def assignment_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to database
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('assignments:list')
    else:
        form = forms.CreateArticle()

    return render(request, 'assignments/assignment_create.html', {'form': form})

matcha/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('Welcome!')
    return render(request, 'homepage.html')


def about(request):
    #return HttpResponse('Hello!')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

assignments/templates/assignments/assignment_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-assignment">
        <h2>Create a New Assignment</h2>
        <form class="site-form" action="{% url 'assignments:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

assignments/templates/assignments/assignment_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="assignment-detail">
        <div class="assignment">
            <img src="{{ assignment.thumb.url }}">
            <h2>{{ assignment.title }}</h2>
            <p>{{ assignment.body }}</p>
            <p>{{ assignment.date }}</p>
        </div>
    </div>
{% endblock %}

assignments/templates/assignments/assignment_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Assignment List</h1>
    <div class="assignments">
        {% for assignment in assignments %}
            <div class="assignment">
                <h2><a href="{% url 'assignments:detail' slug=assignment.slug %}">{{ assignment.title }}</a></h2>
                <p>{{ assignment.snippet }}</p>
                <p>{{ assignment.date }}</p>
                <p class="author">added by {{ assignment.author }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About us</h1>
    <p>We like Django</p>
</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Assignments</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header class="wrapper">
        <h1><a href="{% url 'home' %}"><img src="{% static 'kis_logo.png' %}" id="kis_logo"></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'assignments:create' %}" id="create">New Assignment</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage</h1>
    <p>/Welcome to Matcha</p>
</body>
</html>